### ISSUE TITLE
Install on windows

### ISSUE THREAD

**Issue by hajimurtaza** [hackerlist/glassdoor#24]
pip install in anaconda gives error with BeautifulSoup3

(base) C:\Users\murta>pip install glassdoor
Collecting glassdoor
  Using cached glassdoor-0.0.8.tar.gz
Requirement already satisfied: requests>=1.1.0 in c:\users\murta\anaconda3\lib\site-packages (from glassdoor)
Collecting BeautifulSoup>=3.2.1 (from glassdoor)
  Using cached BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\murta\AppData\Local\Temp\pip-build-xnnub7vo\BeautifulSoup\setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "Unit tests have failed!")?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\murta\AppData\Local\Temp\pip-build-xnnub7vo\BeautifulSoup\

**Comment by payasparab** [comment]
I had the same issue - were you able to resolve this?

**Comment by mekarpeles** [comment]
This code was never ported to python3 and is long past EOL.
